### ISSUE TITLE
FR: Support validate_xml to perform xml diff against config

### ISSUE THREAD

**Issue by nembery** [PaloAltoNetworks/skilletlib#1]
should support testing against file / inline element / or cherry picked element from file

**Comment by nembery** [comment]
The following examples now work in develop
```yaml
  - name: validate_application_reports
    cmd: validate_xml
    xpath: /config/devices/entry[@name='localhost.localdomain']/deviceconfig/system
    file: device_system.xml
    cherry_pick: update-schedule/statistics-service/application-reports

  - name: validate_statistics_service
    cmd: validate_xml
    xpath: /config/devices/entry[@name='localhost.localdomain']/deviceconfig/system
    file: device_system.xml
    cherry_pick: update-schedule/statistics-service

  - name: validate_update_anti_virus
    cmd: validate_xml
    xpath: /config/devices/entry[@name='localhost.localdomain']/deviceconfig/system/update-schedule/anti-virus
    file: anti_virus.xml
```
