### ISSUE TITLE
FR: Include snippets from another skillet / repo

### ISSUE THREAD

**Issue by nembery** [PaloAltoNetworks/skilletlib#51]
We need the ability 'include' snippets from another skillet that may exist in another repo. This will allow third parties to 'track' skillets and extend them as needed. For example, K-12 skillet will track iron skillet but does not need all the parts of IS. They can depend on the IS repo at a specific release / tag / branch. Then at the snippet level, include a snippet in the desired place. 

for example
```yaml
snippets:
  - name: include_iron_skillet_device_system
    include: pan-ironskillet-panos-v90.hardening_device_system
```

Should also be able to include via wildcard to include all snippets from a specified skillet at a specific point

```yaml
snippets:
  - name: include_iron_skillet
    include: pan-ironskillet-panos-v90.*
```

Another possibility is ranged included like

```yaml
snippets:
  - name: include_iron_skillet
    include: pan-ironskillet-panos-v90.[0-15]
```

A skillet that 'depends' on another, should declare the dependency via a new top-level attribute: depends

This should point to the release / branch / or tag zip file.

```yaml
depends:
  - name: skillletlib
    url: https://github.com/PaloAltoNetworks/skilletlib/archive/master.zip
```

dependencies will be downloaded as a zip file and exploded in a temp dir and skillet loader will be used to locate all skillets in the resulting dir structure. This allows us to keep dependencies walled off from each other and not visible in the top level collections in tools like panhandler. Zip files can be cached based on url
