### ISSUE TITLE
REST skillets do not pass custom headers when operation is 'get'

### ISSUE THREAD

**Issue by nembery** [PaloAltoNetworks/skilletlib#59]
```
snippets:
  - name: Retrieve Remote Network Service IP from Prisma Access
    path: xxx
    operation: GET
    headers:
      header-api-key: xxx
```

The above fails due to two bugs actually: GET is not properly being compared against 'get' and the headers dict is not being passed to the request in the case of a 'GET' operation
